# Disable linting of Dangerfile.
Style/FrozenStringLiteralComment:
  Exclude:
    - 'Dangerfile'
# Customize some cops.
Metrics/LineLength:
  Max: 120
  Exclude:
    - '*.gemspec'
Metrics/ClassLength:
  Max: 140

# The danger_plugin.rb file presents unique challenges, ignore it.
Metrics/MethodLength:
  Exclude:
    - 'lib/danger_plugin.rb'
Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/danger_plugin.rb'

# I just don't like these ones.
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false

# For Ruby 2.2 compatibility
Style/NumericPredicate:
  Enabled: false
